ARG ENVOY
FROM envoyproxy/envoy:$ENVOY

RUN apt-get update && apt-get -q install -y \
    curl
ARG ENVOYARGS
ENV ENVOYARGS $ENVOYARGS
CMD echo "Starting envoy with extra args '$ENVOYARGS'"; /usr/local/bin/envoy -c /etc/front-envoy.yaml --service-cluster front-proxy $ENVOYARGS
