ARG ENVOY
FROM envoyproxy/envoy-alpine:$ENVOY

RUN apk update && apk add python3 py-pip bash curl
RUN python3 --version && pip3 --version
RUN pip3 install -q Flask==0.11.1 requests==2.18.4
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ARG ENVOYARGS
ENV ENVOYARGS $ENVOYARGS
ENTRYPOINT /usr/local/bin/start_service.sh $ENVOYARGS
